var _FRAMEWORK={jquery:{name:"jQuery"},prototype:{name:"prototype"}};var _TOOLBAR_EVENT={LOGIN:{name:"loginEvent"},BEFORE_REFRESH:{name:"refreshEvent"},REFRESH:{name:"refreshEvent"}};var TOOLBAR_INSTANCE=null;function submitForm(){document.loginForm.urlRedirect.value=location.href;return true;}
function init_toolbar_public($){function formatContextUrl(){var domain="[a-zA-Z\\.]*";var regEmptyContext=new RegExp("^http://"+domain+"/?$","g");var regWithContext=new RegExp("^http://"+domain+"/"+domain+"/?$","g");if(regEmptyContext.test(location.href)||regWithContext.test(location.href)){return"";}
return location.href;}
dispatchToRightFramework(function(){jQuery('#urlRedirect').val(formatContextUrl());},function(){$('urlRedirect').value=formatContextUrl();});TOOLBAR_INSTANCE=dispatchToRightFramework(function(){return new com.cadremploi.toolbar.JqToolbar();},function(){return new com.cadremploi.toolbar.PtToolbar();});TOOLBAR_INSTANCE.init_public();}
function init_toolbar(){TOOLBAR_INSTANCE=dispatchToRightFramework(function(){return new com.cadremploi.toolbar.JqToolbar();},function(){return new com.cadremploi.toolbar.PtToolbar();});TOOLBAR_INSTANCE.init();}
com.cadremploi.toolbar.AbstractToolbar=function(){this.init_public=function(){throw"not implemented yet";};this.init=function(){this.refreshBloggingMessages();};this.refreshBloggingMessages=function(){if(this.hasToRefreshBloggingMessage()){this.refreshBloggingMessage();setInterval(this.refreshBloggingMessage,10000);}};this.login_onSuccess=function(data){if(redirectIfNeeded(this.getTargetUrlFromResponse(data))){return;}
this.trigger(_TOOLBAR_EVENT.BEFORE_REFRESH,data);this.refresh(data);this.trigger(_TOOLBAR_EVENT.LOGIN,data);};this.login_onError=function(data){this.refreshToolbarDisplay(data);this.init_public();};this.hasToRefreshBloggingMessage=function(){throw"not implemented yet";};this.refresh=function(data){throw"not implemented yet";};this.refreshToolbarDisplay=function(data){this.trigger(_TOOLBAR_EVENT.REFRESH,data);this.init();};this.refreshBloggingMessage=function(data){throw"not implemented yet";};this.getTargetUrlFromResponse=function(data){throw"not implemented yet";};this.bind=function(bindedEvent){var eventFound=false;for(eventName in this.listeners){if(eventName==bindedEvent.event.name){this.listeners[eventName][this.listeners[eventName].length]=bindedEvent.callback;eventFound=true;break;}}
if(!eventFound){this.listeners[bindedEvent.event.name]=new Array(bindedEvent.callback);}};this.trigger=function(triggeredEvent,data){for(eventName in this.listeners){if(eventName==triggeredEvent.name){for(var i=0;i<this.listeners[eventName].length;i++){this.listeners[eventName][i](data);}
break;}}};};com.cadremploi.toolbar.PtToolbar=function(){this.framework=_FRAMEWORK.prototype;this.listeners={};var _self=this;this.init_public=function(){$("jqAjaxRequestUrlOnFailure").value=_MAPPED_URLS.CANDIDATE_REFRESHTOOLBAR_WITHOUT_CONTEXT;$("loginForm").observe('submit',function(e){Event.stop(e);new Ajax.Request($('loginForm').action,{method:'POST',parameters:$('loginForm').serialize(true),onSuccess:function(data){com.cadremploi.toolbar.PtToolbar.prototype.login_onSuccess.call(_self,data);},onFailure:function(data){com.cadremploi.toolbar.PtToolbar.prototype.login_onError.call(_self,data);}});});};this.getTargetUrlFromResponse=function(data){return data.responseText.evalJSON(true).targetUrl;};this.refresh=function(data){new Ajax.Request(_MAPPED_URLS.CANDIDATE_REFRESHTOOLBAR,{method:'POST',onSuccess:function(data){_self.refreshToolbarDisplay(data);com.cadremploi.toolbar.PtToolbar.prototype.init.call(_self,data);}});};this.refreshToolbarDisplay=function(data){$('jqToolbarContainer').innerHTML=refreshToolbarHtml(data.responseText);com.cadremploi.toolbar.PtToolbar.prototype.refreshToolbarDisplay.call(_self,data);};this.hasToRefreshBloggingMessage=function(){return $('jqToolbarLastBloggingMessage_template')!=null;};this.refreshBloggingMessage=function(){new Ajax.Request(_MAPPED_URLS.CANDIDATE_FIND_LAST_MESSAGE,{method:'POST',onSuccess:_self.refreshBloggingMessage_onSuccess,onFailure:function(){$$('.jqToolbarLastBloggingMessage')[0].update("");}});};this.refreshBloggingMessage_onSuccess=function(data){if(data.responseJSON.form.messageList.length==0){return;}
var message=data.responseJSON.form.messageList[0];if(message.id!=$('jqToolbarLastBloggingMessageId').value){new Effect.Fade($$('.jqToolbarLastBloggingMessage')[0],{duration:0.5,afterFinish:function(){var message=data.responseJSON.form.messageList[0];var template=refreshBloggingMessage(message,$('jqToolbarLastBloggingMessage_template').innerHTML);$$('.jqToolbarLastBloggingMessage')[0].update(template);new Effect.Appear($$('.jqToolbarLastBloggingMessage')[0],{duration:0.5});}});}};this.init=function(){com.cadremploi.toolbar.PtToolbar.prototype.init.call(_self);};this.bind=function(bindedEvent){return com.cadremploi.toolbar.PtToolbar.prototype.bind.call(_self,bindedEvent);};this.trigger=function(triggeredEvent,data){return com.cadremploi.toolbar.PtToolbar.prototype.trigger.apply(_self,[triggeredEvent,data]);};};com.cadremploi.toolbar.PtToolbar.prototype=new com.cadremploi.toolbar.AbstractToolbar();com.cadremploi.toolbar.PtToolbar.prototype.constructor=com.cadremploi.toolbar.PtToolbar;com.cadremploi.toolbar.JqToolbar=function(){this.framework=_FRAMEWORK.jquery;this.listeners=new Array();var _self=this;this.init_public=function(){jQuery("#jqAjaxRequestUrlOnFailure").val(_MAPPED_URLS.CANDIDATE_REFRESHTOOLBAR_WITHOUT_CONTEXT);jQuery("#loginForm").plugAjaxOnForm({success:function(data){com.cadremploi.toolbar.JqToolbar.prototype.login_onSuccess.call(_self,data);},error:function(data){com.cadremploi.toolbar.JqToolbar.prototype.login_onError.call(_self,data);}});};this.refresh=function(data){jQuery(this).sendAjaxRequest({url:_MAPPED_URLS.CANDIDATE_REFRESHTOOLBAR,dataType:"html",success:_self.refreshToolbarDisplay});};this.getTargetUrlFromResponse=function(data){return data.targetUrl;};this.refreshToolbarDisplay=function(data){jQuery('#jqToolbarContainer').html(refreshToolbarHtml(getJQueryResponse(data)));com.cadremploi.toolbar.JqToolbar.prototype.refreshToolbarDisplay.call(_self,data);};this.hasToRefreshBloggingMessage=function(){return jQuery('#jqToolbarLastBloggingMessage_template').length>0;};this.refreshBloggingMessage=function(){jQuery(this).sendAjaxRequest({url:_MAPPED_URLS.CANDIDATE_FIND_LAST_MESSAGE,success:_self.refreshBloggingMessage_onSuccess,error:function(){jQuery('.jqToolbarLastBloggingMessage').html("");}});};this.refreshBloggingMessage_onSuccess=function(data){if(data.form.messageList.length==0){return;}
var message=data.form.messageList[0];if(message.id!=jQuery('#jqToolbarLastBloggingMessageId').val()){jQuery('.jqToolbarLastBloggingMessage').fadeOut('fast',function(){var message=data.form.messageList[0];var template=refreshBloggingMessage(message,jQuery('#jqToolbarLastBloggingMessage_template').html());jQuery('.jqToolbarLastBloggingMessage').html(template);jQuery('.jqToolbarLastBloggingMessage').fadeIn('fast');});}};this.init=function(){com.cadremploi.toolbar.JqToolbar.prototype.init.call(_self);};this.bind=function(bindedEvent){return com.cadremploi.toolbar.JqToolbar.prototype.bind.call(_self,bindedEvent);};this.trigger=function(triggeredEvent,data){return com.cadremploi.toolbar.JqToolbar.prototype.trigger.apply(_self,[triggeredEvent,data]);};};com.cadremploi.toolbar.JqToolbar.prototype=new com.cadremploi.toolbar.AbstractToolbar();com.cadremploi.toolbar.JqToolbar.prototype.constructor=com.cadremploi.toolbar.JqToolbar;function dispatchToRightFramework(jqFunc,ptFunc){if(typeof(jQuery)!="undefined"){return jqFunc();}else if(typeof(Prototype)!="undefined"){return ptFunc();}else{}}
function refreshToolbarHtml(data){var startTag="<div id=\"jqToolbarContainer\">";var endTag="jqToolbarContainerEnd\"/>";var start=data.indexOf(startTag)+startTag.length;var end=data.lastIndexOf(endTag)+endTag.length;return data.substring(start,end);}
function refreshBloggingMessage(message,html){var htmlWithMessageLink=html;if(message.username!=null){htmlWithMessageLink=html.replace('#author',encodeUrlTag('<a href="http://profil.cadremploi.fr/#username">#author</a>'));}
htmlWithMessageLink=htmlWithMessageLink.replace('#content',encodeUrlTag(message.content)).replace('#date',message.displayedModificationDate).replace('#id',message.id).replace('#username',message.username);var author=message.author;if(author==null){author="Un internaute";}
return htmlWithMessageLink.replace('#author',author);}
function redirectIfNeeded(targetUrl){var contextualUrl=getContextualUrl(targetUrl);if(location.href!=targetUrl&&location.href!=contextualUrl){location.href=((targetUrl.substring(0,4)=="http")?targetUrl:contextualUrl);return true;}
return false;}
function getJQueryResponse(data){if(data.responseText!=null){return data.responseText;}else{return data;}}
function addXtclick(a,alt){return xt_click(a,'C','2',alt,'A');}